// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV778FOVQC3gvfcDOTdoxnNO-xr01gkTY',
    appId: '1:152211587409:web:be1c59c1dd59416194d370',
    messagingSenderId: '152211587409',
    projectId: 'prophetpath-6efd8',
    authDomain: 'prophetpath-6efd8.firebaseapp.com',
    storageBucket: 'prophetpath-6efd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfPNUwHgpebN3bo1iDbkOHEf4MT-sj0M0',
    appId: '1:152211587409:android:7c25b3124841a4f294d370',
    messagingSenderId: '152211587409',
    projectId: 'prophetpath-6efd8',
    storageBucket: 'prophetpath-6efd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRb-oeusfnxyLQdTZtQEU2dilnt4xJPzk',
    appId: '1:152211587409:ios:13ae0a691bc4b3cd94d370',
    messagingSenderId: '152211587409',
    projectId: 'prophetpath-6efd8',
    storageBucket: 'prophetpath-6efd8.appspot.com',
    iosClientId: '152211587409-3a4gsm9oh0vosfm578ij2nba93tomfbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.prophetspath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRb-oeusfnxyLQdTZtQEU2dilnt4xJPzk',
    appId: '1:152211587409:ios:13ae0a691bc4b3cd94d370',
    messagingSenderId: '152211587409',
    projectId: 'prophetpath-6efd8',
    storageBucket: 'prophetpath-6efd8.appspot.com',
    iosClientId: '152211587409-3a4gsm9oh0vosfm578ij2nba93tomfbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.prophetspath',
  );
}
